### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by KrakenTales** [nandanhere/autodrawer#1]
Traceback (most recent call last):
  File "C:\Users\Patrick\Desktop\autodrawer-main\main.py", line 169, in <module>

    colordict[hex] = colorvalues[roundColor(r,g,b)]
  File "C:\Users\Patrick\Desktop\autodrawer-main\main.py", line 155, in roundCol
or
    (a,bb,c) = colorvalues[i]
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by nandanhere** [comment]
Are all your imports properly imported? could you check if you clicked on the edge of the screen?

**Comment by KrakenTales** [comment]
I have no any error messages about imports issues, mouse always somewhere near center of the screen. My python is 3.8.10. I should mentioned it before.
Also I've get another message after clicked "Click to start"

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Patrick\Desktop\autodrawer-main\tkinter_custom_button.py", line 276, in clicked
    self.on_leave()
  File "C:\Users\Patrick\Desktop\autodrawer-main\tkinter_custom_button.py", line 263, in on_leave
    self.canvas.itemconfig(part, fill=self.fg_color, width=0)
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 2903, in itemconfigure
    return self._configure(('itemconfigure', tagOrId), cnf, kw)
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))_tkinter.TclError: invalid command name ".!tkintercustombutton.!canvas"

**Comment by nandanhere** [comment]
I have noticed that error. but it doesnt affect the usability of the program. i am working on it. however the first issue must not occur. could you trace what you did to get this error?

**Comment by KrakenTales** [comment]
I opened MS Paint, then through CMD in Windows 7x64 ran the main.py from the folder "autodrawer-main", with the default settings I proceed clicked on the button "Click to start", then according to instructions have chosen color from MS Paint palette and clicked to the canvas, than I've got the first error.

**Comment by nandanhere** [comment]
Okay so i fixed the issue. it had to do with pixel values. try the program now

**Comment by KrakenTales** [comment]
Eh, i've tried with updated version and face to a bit different error log. May it be because of using MS Paint instead of Scribble?

C:\Users\Patrick\Desktop\autodrawer-main>C:\Users\Patrick\Desktop\autodrawer-main\main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python38\lib\tkinter\__in
it__.py", line 1892, in __call__  return self.func(*args)
  File "C:\Users\Patrick\Desktop\autodrawer-main\tkinter_custom_button.py", line 276, in clicked
    self.on_leave()
  File "C:\Users\Patrick\Desktop\autodrawer-main\tkinter_custom_button.py", line 263, in on_leave
    self.canvas.itemconfig(part, fill=self.fg_color, width=0)
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 2903, in itemconfigure
    return self._configure(('itemconfigure', tagOrId), cnf, kw)
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))_tkinter.TclError: invalid command name ".!tkintercustombutton.!canvas"
Traceback (most recent call last):
  File "C:\Users\Patrick\Desktop\autodrawer-main\main.py", line 175, in <module>
    colordict[hex] = colorvalues[roundColor(r,g,b)]
  File "C:\Users\Patrick\Desktop\autodrawer-main\main.py", line 161, in roundColor
    (a,bb,c) = colorvalues[i]
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by nandanhere** [comment]
the issue might be fixed now ... give it a try!

**Comment by KrakenTales** [comment]
Yess, now it works!

**Comment by KrakenTales** [comment]
Is that possible to add an ability to indicate not just a string with colors but precise colors on palette? I mean that different programs have their individual positions for colors on palette, so it might be great to universalize the script.

**Comment by nandanhere** [comment]
The code can get the colors of most applications which have a horizontal palette, if that is what you mean. to make it work across all applications either we would have to know the layout of different apps, or make the user click on each color manually. but that would just make it more difficult to use.

**Comment by KrakenTales** [comment]
So as far as I understand you pursue the idea of easy to use program, in that case you're definitely right, thank you for prompt reply!
